name: Build and Release

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request_target.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Configurate environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          BRANCH: release
          FOLDER: out
          CLEAN: true
